/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FalconDemo1 */

#ifndef _Included_FalconDemo1
#define _Included_FalconDemo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FalconDemo1
 * Method:    keygens
 * Signature: ()Ljava/security/KeyPair;
 */
JNIEXPORT jobject JNICALL Java_FalconDemo1_keygens
  (JNIEnv *, jclass);

/*
 * Class:     FalconDemo1
 * Method:    sign
 * Signature: ([B[BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_FalconDemo1_sign
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     FalconDemo1
 * Method:    verify
 * Signature: ([B[BI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_FalconDemo1_verify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
