name: Test Falcon using CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Get Dependency
      run: git submodule update --init
    - name: Setup Compiler
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
        sudo apt-get install -y libgmp-dev
    - name: Execute Tests
      run: make
    - name: Cleanup
      run: make clean
